language: python

sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"

virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
      - python-lxml

install:
  - sed -i '/lxml/d' requirements.txt
  - pip install -r requirements.txt

env:
  global:
    - OTRA=PTRAA
  matrix:
    - DEPLOY=X

script:
  - ./bot.py

after_success:
  - echo "I finished fine"
